BASE=/home/scanner
ARCHIVE_DIR=$BASE/archive/
MONITOR_DIR=$BASE/scanner/
LOG_FILE=$BASE/apps/log/dochauser.log
SIGNAL_NUMBER=+41445008346
SIGNAL_VERSION=signal-cli-0.10.3-Linux
SIGNAL_GROUP=dZRhXx+fbwTl9QBkPGWeBkHh4UFtOio5suJZQyQ1O0Y=


