version: "3.3"
services:
  dochauserbatch:
    build: .
    volumes:
      - /home/scanner/dochauser_mount/archive:/home/scanner/archive
      - /home/scanner/dochauser_mount/scanner:/home/scanner/scanner
      - /home/scanner/dochauser_mount/import:/home/scanner/import
      - /home/scanner/dochauser_mount/elasticdata:/var/lib/elasticsearch

    ports:
      - "9200:9200"

